### ISSUE TITLE
Create Calculation

### ISSUE THREAD

**Issue by undersen** [zetahawke/mvp-kvar#12]
Al crear un calculation se debe agregar los siguientes campos:

- Nombre
- Tipo de moneda de energy_cost

**Comment by zetahawke** [comment]
@undersen por nombre te refieres a agregar el nombre del cliente o un nombre tipo apodo para el calculo?

**Comment by undersen** [comment]
@zetahawke exacto a un tipo de apodo para el calculo por ejemplo "ala izquierda de maquinarias"
