### ISSUE TITLE
COMO Desarrollador DEBO cumplir los siguientes requerimientos

### ISSUE THREAD

**Issue by zetahawke** [zetahawke/mvp-kvar#5]
Validate
===
Datos de usuario
---
- [x] nombre
- [x] password
- [x] phone
- [x] date ( por omisión que la misma app la ponga )
- [x] company
- [x] address 
- [x] country
- [x] city

Cotización
---
- [x] Costo en dolares o peso chileno ($ KW/h) - se seleccionó peso chileno
- [x] tipo de fase (1 ó 2 ) por omisión 1
- [x] kw * or hp ( esta parte opcional uno u otro) - se seleccionó kw
- [x] amps *
- [x] power factor * (por omisión tiene que comenzar 0,_ _)
- [x] hours day (1-24)*
- [x] days month * 
- [x] photo (optional)

Observaciones
---
- [x] creación de cotizaciones
- [x] agregar motores a la cotización
- [x] mostrar todas las cotizaciones - solo en usuario administrador
- [x] mostrar todos los motores de una cotización en particular
- [x] al realizar la cotizaciones asociar el pdf a esta (a al acotizacion)
- [x] poder visualizar el FDP (Power Factor)

**Comment by undersen** [comment]
a datos de usuario le falta el email del usuario

**Comment by undersen** [comment]
company debe ser opcional
